name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * *"
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: /bin/bash update-docker-image.sh
