name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * *"
  push:
    branches:
    - master
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: /bin/bash update-docker-image.sh ${{ secrets.DOCKERHUB_USER }}
