name: Docker Image CI

on:
  workflow_dispatch:
  schedule:
  - cron: "0 2 * * *"
  push:
    branches:
    - master
jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        name: Login to Docker Hub  
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the Docker image
        run: /bin/bash update-docker-image.sh ${{ secrets.DOCKERHUB_USER }}
